server:
  port: 8080

jwt:
  secret: eyJzdWIiOiIyMDIyMTExNSIsIm5hbWUiOiJiYXNpbHJ5IiwibG92ZXIiOiJoeXVuamkiLCJpYXQiOjE1MTYyMzkwMjJ9
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 2592000

spring:
  application.name: kbslBlog_api
  datasource.url: jdbc:mysql://localhost:3306/kbsl_blog?serverTimezone=UTC
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

env:
  security:
      allowed_origin: http://localhost:3000

logging:
  level:
    org:
      springframework:
        security: INFO
