package com.kbslblog_api.constant.enums;

import lombok.Getter;

@Getter
public enum ErrorCode {
    /* 1000 NOT_FOUND */
    USER_NOT_FOUND(1001, "USER_NOT_FOUND"),
    CODE_NOT_FOUND(1006, "CODE_NOT_FOUND"),
    EXTRA_INFO_NOT_FOUND(1007, "EXTRA_INFO_NOT_FOUND"),
    NOTICE_NOT_FOUND(1008, "NOTICE_NOT_FOUND"),
    FILE_NAME_NOT_FOUND(1009, "FILE_NAME_NOT_FOUND"),
    POST_NOT_FOUND(1010, "POST_NOT_FOUND"),

    /* 2000 NOT_MATCHED */
    PASSWORD_NOT_MATCHED(2001, "PASSWORD_NOT_MATCHED"),
    NEW_PASSWORD_NOT_MATCHED(2002, "NEW_PASSWORD_NOT_MATCHED"),
    CODE_NOT_MATCHED(2003, "CODE_NOT_MATCHED"),

    /* 3000 ALREADY_EXISTS */
    USER_ALREADY_EXISTS(3001, "USER_ALREADY_EXISTS"),
    ID_ALREADY_EXISTS(3002, "ID_ALREADY_EXISTS"),
    EMAIL_ALREADY_EXISTS(3003, "EMAIL_ALREADY_EXISTS"),
    PHONE_NUMBER_ALREADY_EXISTS(3004, "PHONE_NUMBER_ALREADY_EXISTS"),
    GENERAL_ALREADY_EXISTS(3005, "GENERAL_ALREADY_EXISTS"),

    /* 4000 AUTH */
    AUTHENTICATION_FAILED(4001, "AUTHENTICATION_FAILED"),
    AUTHENTICATION_REQUEST_COUNT_EXCEEDED(4002, "AUTHENTICATION_REQUEST_COUNT_EXCEEDED"),

    /* 5000 STATUS */
    USER_STATUS_PENDING(5001, "USER_STATUS_PENDING"),
    USER_STATUS_WITHDRAWAL(5002, "USER_STATUS_WITHDRAWAL"),
    NOTICE_STATUS_EXPIRED(5003, "NOTICE_STATUS_EXPIRED"),

    /* 8000 */
    SMS_SERVICE_UNAVAILABLE(8001, "SMS_SERVICE_UNAVAILABLE"),
    AWS_SERVICE_UNAVAILABLE(8003, "AWS_SERVICE_UNAVAILABLE"),

    /* 9999 UNDEFINED_EXCEPTION */
    EXCEPTION(9999, "UNDEFINED_EXCEPTION");

    final int code;
    final String message;

    ErrorCode(int code, String message) {
        this.code = code;
        this.message = message;
    }
}